### ISSUE TITLE
Wrong bolt-defaults.yaml path in Lesson 3 - Bolt Configuration

### ISSUE THREAD

**Issue by alvagante** [puppetlabs/ilt-getting-started-with-puppet-issues#45]
## Describe the Bug
Line:
The ~/.puppetlabs/bolt/bolt-defaults.yaml file is used to set default configurations for Bolt.

should be:
The ~/.puppetlabs/etc/bolt/bolt-defaults.yaml file is used to set default configurations for Bolt.

Reference:
https://puppet.com/docs/bolt/latest/configuring_bolt.html#user-level-configuration

**Comment by alvagante** [comment]
Maybe worth also showing the different paths for users' defaults (~/.puppetlabs/etc/bolt/bolt-defaults.yaml) and system's defaults (/etc/puppetlabs/bolt/bolt-defaults.yaml)

**Comment by beechtom** [comment]
Ideally, the lesson would introduce the `bolt-project.yaml` file, as that's the file Bolt uses to determine whether a directory is a project or not and is where most users should set configuration. The `bolt-defaults.yaml` file is for common configuration across multiple projects, and generally is only recommended for more advanced users with multiple projects.

The following config is currently suggested for `bolt-defaults.yaml`:

```yaml
# bolt-defaults.yaml
inventory-config:
  transport: winrm
  ssh:
    user: <username>
    password: <password>
  winrm:
    user: <username>
    password:
      _plugin: pkcs7
      encrypted_value: |
        ENC[PKCS7,MY_ENCRYPTED_DATA]
log:
  console:
    level: info
  "~/logs/debug.log":
    append: false
    level: debug
```

For most users, the `log` config would go in `bolt-project.yaml`, while `inventory-config` config would go under the top-level `config` key in the `inventory.yaml` file:

```yaml
# ~/.puppetlabs/bolt/bolt-project.yaml
log:
  console:
    level: info
  "~/logs/debug.log":
    append: false
    level: debug
```

```yaml
# ~/.puppetlabs/bolt/inventory.yaml
config:
  transport: winrm
  ssh:
    user: <username>
    password: <password>
  winrm:
    user: <username>
    password:
      _plugin: pkcs7
      encrypted_value: |
        ENC[PKCS7,MY_ENCRYPTED_DATA]
```
